name: jwt_decoder
description: >-
  This small library helps you to decode Json Web Tokens,
  you can also know if a JWT is already expired.
version: 2.0.2
homepage: https://github.com/gustavo0197/dart-jwt-decoder

environment:
  sdk: ">=2.12.0 <4.0.0"

dev_dependencies:
  test: ^1.16.5
